openapi: 3.0.1
info:
  title: Hello World API
  version: 1.0.0
  description: A simple API that returns "Hello, World!"
paths:
  /api/hello:
    get:
      summary: Returns a Hello World message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!